name: Verify and Deploy Portfolio
on:
  push:
    branches: [Development]
  pull_request:
    branches: [Development]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Build Portfolio
        env:
          CONTACT_API_URL: ${{ secrets.CONTACT_API_URL }}
        run: |
          npm ci
          npm run build-prod
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: master
          FOLDER: dist
